name: Mabl Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Mabl Tests
        uses: mablhq/github-run-tests-action@v1
        with:
          application-id: ${{ secrets.MABL_APP_ID }}
          environment-id: ${{ secrets.MABL_ENV_ID }}
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}